check_interval = 60 # How often price should be check and frequency updated, in minutes

[prices]
cheap = 0.3 # Price limit for switching to slow
expensive = 1.8 # Price limit for switching to turbo

# Multiple Bitaxes are supported
[[bitaxes]]
host = "192.168.8.1"
slow = 50 # GH/s to use in slow mode
normal = 500 # GH/s to use in normal mode

[[bitaxes]]
host = "192.168.8.2"
slow = 50
normal = 550
